/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
static yyconst short int yy_acclist[296] =
    {   0,
       70,   68,   69,   69,   52,   68,   69,   49,   68,   69,
       68,   69,   68,   69,   68,   69,   33,   68,   69,   48,
       68,   69,   69,   35,   68,   69,   36,   68,   69,   31,
       68,   69,   29,   68,   69,   45,   68,   69,   30,   68,
       69,   46,   68,   69,   32,   68,   69,    5,   68,   69,
        4,   68,   69,   47,   68,   69,   44,   68,   69,   42,
       68,   69,   43,   68,   69,   41,   68,   69,   51,   68,
       69,   28,   68,   69,   28,   68,   69,   39,   68,   69,
       40,   68,   69,   34,   68,   69,   28,   68,   69,   28,
       68,   69,   28,   68,   69,   28,   68,   69,   28,   68,

       69,   28,   68,   69,   28,   68,   69,   28,   68,   69,
       28,   68,   69,   28,   68,   69,   28,   68,   69,   28,
       68,   69,   28,   68,   69,   28,   68,   69,   28,   68,
       69,   28,   68,   69,   37,   68,   69,   68,   69,   38,
       68,   69,   50,   68,   69,   56,   10,   27,   54,    9,
       63,   59,   61,   60,   62,   65,    7,   66,   64,    7,
        5,    4,   58,   55,   57,   28,   28,   28,   28,   28,
       28,   28,   28,   18,   28,   28,   28,   28,   28,   28,
       14,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   53,   27,    9,    7,   66,    7,

        6,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   19,   28,   28,   11,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
        7,   67,    7,    8,   28,   12,   28,   28,   23,   28,
       28,   28,   28,   15,   28,   28,   28,   26,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   21,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   13,   28,   17,   28,   28,   28,   28,   20,
       28,   25,   28,   16,   28,   28,    1,   28,   24,   28,
       28,   22,   28,    3,    2

    } ;

static yyconst short int yy_accept[241] =
    {   0,
        1,    1,    1,    2,    4,    5,    8,   11,   13,   15,
       17,   20,   23,   24,   27,   30,   33,   36,   39,   42,
       45,   48,   51,   54,   57,   60,   63,   66,   69,   72,
       75,   78,   81,   84,   87,   90,   93,   96,   99,  102,
      105,  108,  111,  114,  117,  120,  123,  126,  129,  132,
      135,  138,  140,  143,  146,  147,  147,  148,  148,  148,
      148,  149,  150,  150,  150,  151,  151,  152,  153,  154,
      155,  156,  157,  158,  158,  159,  160,  161,  162,  162,
      162,  162,  163,  164,  165,  166,  167,  168,  169,  170,
      171,  172,  173,  174,  176,  177,  178,  179,  180,  181,

      183,  184,  185,  186,  187,  188,  189,  190,  191,  192,
      193,  194,  195,  196,  196,  196,  197,  198,  198,  198,
      198,  199,  199,  199,  200,  200,  201,  202,  203,  204,
      205,  206,  207,  208,  209,  210,  211,  212,  213,  215,
      216,  218,  219,  220,  221,  222,  223,  224,  225,  226,
      227,  228,  229,  230,  231,  231,  231,  231,  231,  231,
      232,  233,  234,  236,  238,  239,  241,  242,  243,  244,
      246,  247,  248,  250,  251,  252,  253,  254,  255,  256,
      257,  258,  259,  260,  260,  260,  260,  260,  262,  263,
      264,  265,  266,  267,  268,  269,  270,  271,  272,  273,

      275,  277,  277,  277,  278,  279,  280,  282,  284,  286,
      287,  288,  288,  289,  291,  292,  292,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  295,  295,  296,  296,  296,  296,  296
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   30,   30,   30,   31,   32,
       30,   30,   30,   30,   30,   33,   30,   34,   30,   30,
       30,   30,   30,   30,   35,   30,   30,   36,   30,   30,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   51,   54,
       55,   56,   51,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    5,    5,
        6,    6,    6,    1,    1,    1,    1,    7,    1,    8,
        8,    8,    8,    8,    8,    8,    1,    5,    1,    1,
        9,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[258] =
    {   0,
        0,    0,  532,  555,  555,  555,  501,   63,   26,    0,
      555,  512,   71,  555,  555,  491,   61,  555,   62,   63,
       67,   74,   80,  555,  555,  490,  486,  485,  555,    0,
      474,  555,  555,  555,  447,  447,   49,   60,   54,   26,
      446,   65,  437,  419,  429,   72,  388,  397,  394,  392,
      555,  372,  555,  555,  555,  107,  555,  116,  392,  383,
        0,  555,  424,  417,  555,  106,  555,  555,  555,  555,
      555,  555,  117,  413,    0,  555,  120,  137,  153,  164,
        0,  169,  555,  555,  555,    0,  393,  359,  371,  358,
      373,  360,  366,  347,  348,  346,  349,  346,  343,    0,

      342,  346,  346,   76,  343,  332,   88,  344,  337,  341,
      333,  331,  555,  333,  335,    0,  366,  181,    0,  188,
      555,  356,  142,    0,  156,  175,    0,  337,  313,  318,
      313,  301,  298,  314,  312,  303,  302,  305,    0,  291,
        0,  297,  291,  293,  282,  284,  294,  280,  275,  274,
      279,  268,  277,  260,  262,  257,  202,  290,  195,  198,
      555,  555,    0,    0,  249,    0,  249,  238,  244,    0,
      238,  235,    0,  232,  232,  229,  232,  215,  214,  213,
      211,  201,  207,  196,  189,  232,  231,    0,  188,  179,
      183,  172,  153,  151,  154,  145,  122,  122,  115,    0,

        0,  109,  109,   76,   74,   86,    0,    0,    0,   82,
      555,   62,   54,    0,   35,   73,    0,  220,  127,  175,
      214,  216,  221,  241,  273,  228,  248,  253,  296,  258,
      262,  298,  555,  331,  555,  354,  389,  412,  555,  453,
      455,  464,  468,  472,  481,  490,  494,  497,  502,  506,
      511,  516,  521,  528,  533,  540,  545
    } ;

static yyconst short int yy_def[258] =
    {   0,
      239,    1,  239,  239,  239,  239,  239,  240,  239,  241,
      239,  239,  242,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  243,
      243,  239,  239,  239,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      239,  239,  239,  239,  239,  240,  239,  240,  239,  239,
      244,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  245,  246,  239,  239,  239,  239,  239,
      247,  239,  239,  239,  239,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  239,  239,  239,  244,  239,  239,  248,  239,
      239,  245,  245,  246,  239,  239,  247,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  239,  239,  239,  249,  239,  239,
      239,  239,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  239,  239,  239,  239,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  239,  239,  243,  243,  243,  243,  243,  243,  243,
      239,  239,  243,  243,  243,  239,  243,  239,  250,  251,
      250,  252,  251,  253,  254,  250,  252,  252,  255,  251,
      253,  253,  239,  256,  239,  257,  256,  257,    0,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239
    } ;

static yyconst short int yy_nxt[625] =
    {   0,
        4,    4,    5,    6,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       30,   30,   30,   31,   30,   30,   32,    4,   33,   34,
       30,   35,   36,   37,   38,   39,   40,   41,   30,   42,
       30,   30,   43,   44,   30,   30,   45,   46,   47,   48,
       49,   50,   30,   30,   30,   51,   52,   53,   54,   57,
       59,   58,   64,   64,   64,   60,   68,  218,   97,   70,
       98,   74,   65,   73,   73,   73,   75,   69,   71,   72,
       90,  164,   77,   76,   78,   78,   79,   91,   77,  217,

       82,   82,   82,   92,   80,   93,   95,  216,   66,   81,
       80,  100,   63,   57,   94,   58,   96,  117,  101,   80,
      105,  106,   57,  144,   58,   80,  118,  118,  164,  148,
      107,  215,  214,  108,  145,  213,   81,   73,   73,   73,
       73,   73,   73,   63,  149,  221,  221,  120,  121,  121,
      120,  121,  121,  212,  211,   77,  123,   78,   78,   79,
      210,  161,  120,  121,  221,  120,  121,   80,  119,  121,
      209,   77,  121,   79,   79,   79,  126,  126,  126,  125,
      200,  125,   80,   80,  126,  126,  126,   77,  164,   82,
       82,   82,   65,  223,  223,  126,  126,  126,   80,   80,

      208,  157,  157,  159,  207,  159,  162,  162,  160,  160,
      160,  206,  223,   65,   80,  160,  160,  160,  160,  160,
      160,  162,  186,  186,  218,  164,  219,  162,  141,  121,
      121,  205,  221,  221,  225,  226,  227,  227,  227,  223,
      223,  204,   65,   65,  121,  220,  225,  226,  203,  202,
      121,  221,  201,  226,  200,  199,  198,  197,  223,  229,
      230,  231,  231,  231,  196,  226,  225,  226,  227,  227,
      227,  225,  226,  227,  227,  227,  229,  230,  230,  233,
      229,  230,  231,  231,  231,  226,  195,  141,  194,  193,
      226,  221,  221,  141,  192,  230,  191,  190,  189,  230,

      188,   65,  222,  222,  222,  222,  222,  222,  222,  185,
      221,  184,  183,  222,  223,  223,  229,  230,  231,  231,
      231,  141,  182,  235,  181,  224,  224,  224,  224,  224,
      224,  224,  180,  223,  179,  230,  224,  233,  178,  177,
      176,  175,  174,  163,  141,  173,  172,  171,  170,  225,
      226,  227,  227,  227,  169,  168,  167,  141,  166,  165,
      228,  228,  228,  228,  228,  228,  228,  164,  226,  163,
      123,  228,  229,  230,  231,  231,  231,   65,  156,  155,
      154,  235,  153,  232,  232,  232,  232,  232,  232,  232,
      152,  230,  151,  150,  232,  233,  147,  146,  143,  142,

      141,  140,  139,  138,  137,  136,  135,  225,  226,  227,
      227,  227,  134,  133,  132,  131,  130,  129,  228,  228,
      228,  228,  228,  228,  228,  128,  226,  123,   65,  228,
      229,  230,  231,  231,  231,   65,  115,  114,  113,  235,
      112,  232,  232,  232,  232,  232,  232,  232,  111,  230,
      110,  109,  232,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   61,   61,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   86,  104,   86,   86,  116,  103,  116,
      116,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      124,  102,  124,  124,  124,  124,  124,  124,  124,  127,

       99,  127,  158,   89,  158,  187,   88,  187,   87,  187,
      222,   85,   84,  222,  222,  224,   83,   67,  224,  224,
      228,  228,   62,  228,  228,  232,  232,   55,  232,  232,
      234,  239,  234,  239,  239,  234,  234,  236,  239,  236,
      236,  236,  237,  239,  237,  237,  239,  237,  237,  238,
      238,  238,  238,  238,    3,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239
    } ;

static yyconst short int yy_chk[625] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
        9,    8,   13,   13,   13,    9,   17,  216,   40,   19,
       40,   21,   13,   20,   20,   20,   21,   17,   19,   19,
       37,  215,   22,   21,   22,   22,   22,   37,   23,  213,

       23,   23,   23,   37,   22,   38,   39,  212,   13,   22,
       23,   42,   66,   56,   38,   56,   39,   66,   42,   22,
       46,   46,   58,  104,   58,   23,   66,   66,  210,  107,
       46,  206,  205,   46,  104,  204,   22,   73,   73,   73,
       77,   77,   77,   66,  107,  219,  219,   73,   73,   73,
       77,   77,   77,  203,  202,   78,  123,   78,   78,   78,
      199,  123,   73,   73,  219,   77,   77,   78,   66,   73,
      198,   79,   77,   79,   79,   79,  125,  125,  125,   80,
      197,   80,   78,   79,   80,   80,   80,   82,  196,   82,
       82,   82,  118,  220,  220,  126,  126,  126,   79,   82,

      195,  118,  118,  120,  194,  120,  126,  126,  120,  120,
      120,  193,  220,  157,   82,  159,  159,  159,  160,  160,
      160,  126,  157,  157,  218,  192,  218,  126,  191,  160,
      160,  190,  221,  221,  222,  222,  222,  222,  222,  223,
      223,  189,  187,  186,  160,  218,  226,  226,  185,  184,
      160,  221,  183,  222,  182,  181,  180,  179,  223,  224,
      224,  224,  224,  224,  178,  226,  227,  227,  227,  227,
      227,  228,  228,  228,  228,  228,  230,  230,  224,  225,
      231,  231,  231,  231,  231,  227,  177,  176,  175,  174,
      228,  225,  225,  172,  171,  230,  169,  168,  167,  231,

      165,  158,  225,  225,  225,  225,  225,  225,  225,  156,
      225,  155,  154,  225,  229,  229,  232,  232,  232,  232,
      232,  153,  152,  229,  151,  229,  229,  229,  229,  229,
      229,  229,  150,  229,  149,  232,  229,  234,  148,  147,
      146,  145,  144,  143,  142,  140,  138,  137,  136,  234,
      234,  234,  234,  234,  135,  134,  133,  132,  131,  130,
      234,  234,  234,  234,  234,  234,  234,  129,  234,  128,
      122,  234,  236,  236,  236,  236,  236,  117,  115,  114,
      112,  236,  111,  236,  236,  236,  236,  236,  236,  236,
      110,  236,  109,  108,  236,  237,  106,  105,  103,  102,

      101,   99,   98,   97,   96,   95,   94,  237,  237,  237,
      237,  237,   93,   92,   91,   90,   89,   88,  237,  237,
      237,  237,  237,  237,  237,   87,  237,   74,   64,  237,
      238,  238,  238,  238,  238,   63,   60,   59,   52,  238,
       50,  238,  238,  238,  238,  238,  238,  238,   49,  238,
       48,   47,  238,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  241,  241,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  243,   45,  243,  243,  244,   44,  244,
      244,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      246,   43,  246,  246,  246,  246,  246,  246,  246,  247,

       41,  247,  248,   36,  248,  249,   35,  249,   31,  249,
      250,   28,   27,  250,  250,  251,   26,   16,  251,  251,
      252,  252,   12,  252,  252,  253,  253,    7,  253,  253,
      254,    3,  254,    0,    0,  254,  254,  255,    0,  255,
      255,  255,  256,    0,  256,  256,    0,  256,  256,  257,
      257,  257,  257,  257,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ejemplo.l"
#define INITIAL 0
#line 4 "ejemplo.l"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "ejemplo.tab.h"

#line 635 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 49 "ejemplo.l"


#line 789 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 240 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 555 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 51 "ejemplo.l"
{strcpy(yylval.cval,yytext); return DEFINE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "ejemplo.l"
{strcpy(yylval.cval,yytext); return INCLUDE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "ejemplo.l"
{strcpy(yylval.cval,yytext); return INCLUDE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "ejemplo.l"
{yylval.ival = atoi(yytext); return ENTERO; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "ejemplo.l"
{yylval.ival = strtol(yytext, NULL, 0); return ENTERO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "ejemplo.l"
{yylval.ival = strtol(yytext, NULL, 0); return ENTERO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "ejemplo.l"
{yylval.dval = atof(yytext); return REAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "ejemplo.l"
{strcpy(yylval.cval,yytext); return NULL1; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "ejemplo.l"
{strcpy(yylval.cval,yytext); return CTE_CARACTER; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "ejemplo.l"
{strcpy(yylval.cval,yytext); return LITERAL_CADENA; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "ejemplo.l"
{strcpy(yylval.cval,yytext); return TIPO_DATO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "ejemplo.l"
{strcpy(yylval.cval,yytext); return CLASE_ALMACENAMIENTO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "ejemplo.l"
{strcpy(yylval.cval,yytext); return STRUCT_UNION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "ejemplo.l"
{return IF; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "ejemplo.l"
{return ELSE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "ejemplo.l"
{return SWITCH; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "ejemplo.l"
{return WHILE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "ejemplo.l"
{return DO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "ejemplo.l"
{return FOR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "ejemplo.l"
{return RETURN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "ejemplo.l"
{return BREAK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "ejemplo.l"
{return CONTINUE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "ejemplo.l"
{return CASE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "ejemplo.l"
{return DEFAULT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "ejemplo.l"
{return SIZEOF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "ejemplo.l"
{return GOTO; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "ejemplo.l"
{strcpy(yylval.cval,yytext); return IDBIS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "ejemplo.l"
{strcpy(yylval.cval,yytext); return ID;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 84 "ejemplo.l"
{return '+'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "ejemplo.l"
{return '-'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "ejemplo.l"
{return '*'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "ejemplo.l"
{return '/'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "ejemplo.l"
{return '%'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "ejemplo.l"
{return '^'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "ejemplo.l"
{return '('; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "ejemplo.l"
{return ')'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "ejemplo.l"
{return '{'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "ejemplo.l"
{return '}'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 "ejemplo.l"
{return '['; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 95 "ejemplo.l"
{return ']'; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 "ejemplo.l"
{return '>'; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 "ejemplo.l"
{return '<'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 "ejemplo.l"
{return '='; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 99 "ejemplo.l"
{return ';'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 100 "ejemplo.l"
{return ','; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 101 "ejemplo.l"
{return '.'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 102 "ejemplo.l"
{return ':'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 103 "ejemplo.l"
{return '&'; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 104 "ejemplo.l"
{return '!'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 105 "ejemplo.l"
{return '~'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 106 "ejemplo.l"
{return '?'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 107 "ejemplo.l"
{return '\n'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 109 "ejemplo.l"
{return OR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 110 "ejemplo.l"
{return AND; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 111 "ejemplo.l"
{return IGUALDAD; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 112 "ejemplo.l"
{return DESIGUALDAD; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 113 "ejemplo.l"
{return MAYORIGUAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 114 "ejemplo.l"
{return MENORIGUAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 115 "ejemplo.l"
{return INCREMENTO; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 116 "ejemplo.l"
{return DECREMENTO; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 117 "ejemplo.l"
{return ASIGNACION_INCREMENTO; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 118 "ejemplo.l"
{return ASIGNACION_DECREMENTO; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "ejemplo.l"
{return ASIGNACION_PRODUCTO; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 120 "ejemplo.l"
{return ASIGNACION_DIVISION; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 121 "ejemplo.l"
{return FLECHA; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 124 "ejemplo.l"
{strcpy(yylval.cval,yytext); return COMENTARIO_SIMPLE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 125 "ejemplo.l"
{strcpy(yylval.cval,yytext); return COMENTARIO_MULTIPLE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 "ejemplo.l"
{strcpy(yylval.cval,yytext); return ERROR_LEXICO;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 129 "ejemplo.l"
ECHO;
	YY_BREAK
#line 1225 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 240 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 240 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 239);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 129 "ejemplo.l"
